name: Arduino Lint

on:
  push:
    branches:
      - main
  pull_request:

# The concurrency spec means that we'll only run one set of jobs per pull request or push to main.
# If a new push or pull request comes in while a job is running, all jobs in the concurrency group will be cancelled.
concurrency:
  group: arduino-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          compliance: strict
          library-manager: update
          project-type: library
