name: Build

on:
  push:
    branches:
      - main
  pull_request:

# The concurrency spec means that we'll only run one set of jobs per pull request or push to main.
# If a new push or pull request comes in while a job is running, all jobs in the concurrency group will be cancelled.
concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [test-native]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            .pio/libdeps
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build ${{ matrix.platform }}
        id: build
        run: |
          pio run -e ${{ matrix.platform }}
